process.env.TWITTER_CONSUMER_KEY = 'wjJzOeCTa3NgIwpng7uBbtP0o';
process.env.TWITTER_CONSUMER_SECRET = 'mFY7YGOkj9LwITBBXdjj4sGsJ3auLaZyDyQr7gGoZ0EEAdzEQD';
process.env.TWITTER_ACCESS_TOKEN_KEY = '4569267073-rwUTZglZLMoKUTrTllluJq3zzGJK2uQ4lBRJkpJ';
process.env.TWITTER_ACCESS_TOKEN_SECRET = 'eAwPJybDLYq0G3N5qYivzX3JO6jpiWJ5rO9zpp1LDTsfp';